spring:
  application:
    name: generator-worker-starter

pockethive:
  worker:
    inputs:
      autowire: true
  inputs:
    scheduler:
      enabled: true
  outputs:
    rabbit:
      exchange: ph.sample-swarm.hive
      routingKey: ph.sample-swarm.mod
  control-plane:
    exchange: ph.control
    swarm-id: sample-swarm
    instance-id: ${POCKETHIVE_CONTROL_PLANE_INSTANCE_ID:generator-1}
    control-queue-prefix: ph.control
    worker:
      role: generator
  workers:
    generator:
      config:
        ratePerSecond: 1.0
        message: "Hello from the generator"
