spring:
  application:
    name: generator-worker-starter

pockethive:
  worker:
    inputs:
      autowire: true
  inputs:
    generator:
      enabled: true
  control-plane:
    exchange: ph.control
    traffic-exchange: ph.sample-swarm.hive
    swarm-id: sample-swarm
    instance-id: ${POCKETHIVE_CONTROL_PLANE_INSTANCE_ID:generator-1}
    queues:
      generator: ph.sample-swarm.gen
      moderator: ph.sample-swarm.mod
      final: ph.sample-swarm.final
    worker:
      role: generator
  workers:
    generator:
      config:
        ratePerSecond: 1.0
        message: "Hello from the generator"
