spring:
  application:
    name: processor-worker-starter

pockethive:
  worker:
    inputs:
      autowire: true
  inputs:
    rabbit:
      queue: ph.sample-swarm.mod
  outputs:
    rabbit:
      exchange: ph.sample-swarm.hive
      routingKey: ph.sample-swarm.final
  control-plane:
    exchange: ph.control
    swarm-id: sample-swarm
    instance-id: ${POCKETHIVE_CONTROL_PLANE_INSTANCE_ID:processor-1}
    control-queue-prefix: ph.control
    worker:
      role: processor
