apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090/prometheus/
    isDefault: true
  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
  - name: PocketHive Journal (Postgres)
    type: postgres
    access: proxy
    url: postgres:5432
    user: pockethive
    database: pockethive
    jsonData:
      database: pockethive
      sslmode: disable
      postgresVersion: 1600
      timescaledb: false
    secureJsonData:
      password: pockethive
  - name: ClickHouse
    uid: clickhouse
    type: grafana-clickhouse-datasource
    access: proxy
    jsonData:
      protocol: http
      host: clickhouse
      port: 8123
      username: pockethive
      defaultDatabase: default
      tlsSkipVerify: false
    secureJsonData:
      password: pockethive
